version: "3.7"

services:
  inventory:
    build: ./inventory
    env_file:
      - ./inventory/.env
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./inventory:/app/
    depends_on:
      - inventory_db
      - redis
  inventory-frontend:
    build: ./inventory-frontend
    env_file:
      - ./inventory-frontend/.env
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - inventory
      - payment
  payment:
    build: ./payment
    env_file:
      - ./payment/.env
    ports:
      - "8081:8081"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./payment:/app/
    depends_on:
      - payment_db
      - redis
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - payment_db
      - inventory_db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  payment_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
  inventory_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
